FROM mysql:8.0
EXPOSE 3306




# docker build --progress=plain -t mysqldb:v1 .

# docker run -d \
#   --name mysqldb-c \
#   --restart unless-stopped \
#   --network roboshop \
#   -p 3306:3306 \
#   -v mysql-data:/var/lib/mysql \
#   -e MYSQL_ROOT_PASSWORD='RoboShop@1' \
#   mysqldb:v1
