FROM mysql:8
EXPOSE 3306




# docker build --progress plain -t mysql:v1 .

# docker run -d \
#   --name mysqldb \
#   -v mysql-data:/var/lib/mysql \
#   -e MYSQL_ROOT_PASSWORD='RoboShop@1' \
#   mysql:v1