FROM alpine:3.20
ENTRYPOINT ["echo","Hi"]
CMD ["Jansi"]


# entrypoint is main executable which runs at container starting
# and command is default executabel and default arugments 


# [ec2-user@ip-172-31-1-179 ex6]$ docker run --name entry-cmd  entrypoint-cmd:v1 
# Hi Jansi
# [ec2-user@ip-172-31-1-179 ex6]$ docker run --name entry-cmd  entrypoint-cmd:v1 jahnavi
# Hi jahnavi