FROM rabbitmq:3

EXPOSE 5672 15672





# docker run -d \
#   --name rabbitmq \
#   --restart unless-stopped \
#   -p 5672:5672 \
#   -p 15672:15672 \
#   -e RABBITMQ_DEFAULT_USER=roboshop \
#   -e RABBITMQ_DEFAULT_PASS=roboshop123 \
#   -v rabbitmq-data:/var/lib/rabbitmq \
#   rabbitmq-db


#   RabbitMQ application port. 5672
#   RabbitMQ web UI port. 15672