name: compose project demo
services:
   web:
     build:
      context: .
      dockerfile: Dockerfile
    # docker build . -->creates image
     ports:
       - "${APP_PORT :- 8080}:5000"
     environment:
          APP_ENV: "${APP_ENV:-development}"
          REDIS_HOST: redis     #container in same network can comminicate to other using servicename(compose dns will resolve)
          REDIS_PORT: "6379"    #redis listening on redis-ip:redis-port
     networks:
        - application-network
     depends_on:
         redis:
            condition: service_healthy        #create this container only after redis container is created and is healthy
   redis:
    image: redis:alpine     #image exists locally pr in registry
    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - application-network         


volumes:
   redis-data:
networks:
  application-network:
    driver: bridge   
 
